# Week 1 Assignment
## Basic Data Exploration and Cleaning using Pandas

### Submitted By:
Nikita Bansode - Sanjivani College Of Engineering

### Objective
Learn Python basics and perform basic data exploration and cleaning using Pandas. Steps: 1.Load a CSV dataset into a Pandas DataFrame. 2.Explore data (head/tail, shape, columns, data types). 3.Handle missing values (identify, fill/drop). 4.Perform basic operations (filter rows, select columns). 5.Remove duplicates. 6.Create a derived column (total_amount = price * quantity). 7.Save the cleaned dataset as a new CSV file. Output: Jupyter Notebook (.ipynb) + cleaned CSV + brief summary."
Resources :
https://www.kaggle.com/datasets/anvitkumar/shopping-dataset

## 1. Load a CSV dataset into a Pandas DataFrame.

In [4]:
#Importing required libraries
import pandas as pd
import numpy as np

In [5]:
#Load the dataset
df = pd.read_csv("C:\\Users\\HP\\Desktop\\Celebal_Assignments\\Combined_dataset.csv")

## 2. Explore data (head/tail, shape, columns, data types).

In [6]:
#Initial data exploration
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [7]:
#Dataset Shape
df.shape

(1000, 24)

In [8]:
#Column Analysis
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [9]:
#Data Types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

## 3. Handle missing values (identify, fill/drop).

In [10]:
#Find Missing values
df.isnull()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False

In [11]:
#Sum of Missing Values
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [14]:
df[['discount','seller_name','sizes','variations','best_offer']].head(20)

,discount,seller_name,sizes,variations,best_offer
0,58.0,NaN,"[{""size"":""Onesize""}]",[{}],{}
1,35.0,NaN,"[{""size"":""Onesize""}]","[{},{}]",{}
2,65.0,NaN,"[{""size"":""S""}]","[{},{},{},{},{},{}]",{}
3,52.0,NaN,"[{""size"":""Onesize""}]",NaN,{}
4,17.0,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{}
5,NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]","[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ..."
6,65.0,NaN,"[{""size"":""Onesize""}]","[{},{}]",{}
7,54.0,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",[{}],{}
8,54.0,NaN,"[{""size"":""Super King""}]",[{}],{}
9,53.0,NaN,"[{""size"":""Double King""}]","[{},{}]",{}
10,46.0,NaN,"[{""size"":""Double Queen""}]","[{},{},{},{},{},{},{}]",{}
11,74.0,Sig███Ove███as,"[{""size"":""Super King""}]","[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o..."
12,73.0,Bel███Cas███ash█████████ail█████████,"[{""size"":""Single""}]","[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o..."
13,65.0,NaN,"[{""size"":""Double King""}]",[{}],{}
14,20.0,NaN,"[{""size"":""Double King""}]",[{}],{}
15,42.0,NaN,"[{""size"":""Single""},{""size"":""Double Queen""}]","[{},{}]",{}
16,78.0,NaN,"[{""size"":""Double Queen""}]","[{},{},{},{}]",{}
17,76.0,NaN,"[{""size"":""Super King""}]","[{},{},{},{},{},{}]",{}
18,84.0,Kas███r L███her█████████Pvt██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o..."
19,40.0,PVH███VIN███ASH█████████TE ███████████████,"[{""size"":""XXS"",""value"":""21.8in"",""value_name"":""...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ..."

### Missing Value Analysis
The dataset contains missing values in six columns:
- discount
- what_customers_said
- seller_name
- videos
- seller_information
- variations

Since these missing values are primarily present in optional descriptive fields, removing rows would lead to unnecessary data loss. Therefore, meaningful replacement values are used to preserve the dataset while improving data quality.

In [21]:
#Handling Missing Values

#Filling the missing values in discount as '0'
df['discount'] = df['discount'].fillna(0)

#Filling the missing values in seller's name as  'Unknown seller'
df['seller_name'] = df['seller_name'].fillna('Unknown Seller')

#Filling the missing values in seller's information as 'Not Available'
df['seller_information'] = df['seller_information'].fillna('Not Available')

#Filling the missing values in variations as 'Not Available'
df['variations'] = df['variations'].fillna('Not Available')

#Dropping the two columns 'videos' and 'what_customers_said'
df.drop(columns=['videos','what_customers_said'], inplace=True)

In [22]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
seller_name               0
sizes                     0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

No missing values are available now. 
Therefore, we sucessfully handled the missing values

Also, The columns videos and what_customers_said contain a high percentage of missing values and are not directly relevant to the objectives of this assignment. Therefore, they were removed to simplify the dataset and focus on business-relevant attributes.

##  4. Perform basic operations (filter rows, select columns).

#### 4.1 Selecting Relevant Columns :
The dataset contains multiple attributes. For analysis purposes, only a subset of important columns was selected.
The selected columns provide information about:
- Product Name
- Product Category
- Customer Rating
- Final Selling Price
  
This makes the dataset easier to analyze and interpret.

In [28]:
selected_columns = df[['title', 'category', 'rating', 'final_price']]
selected_columns.head()

            title   category  rating  final_price
0     Lino Perros  backpacks     3.8  "₹3,995.00"
1  Tommy Hilfiger  backpacks     4.5  "₹2,899.00"
2           Lavie  backpacks     4.4  "₹2,999.00"
3          F Gear  backpacks     4.4  "₹1,675.00"
4       MYTRIDENT  bath-robe     4.7  "₹2,899.00"

#### 4.2 Filtering Rows :
Filtering is used to extract records that satisfy a specific condition.
In this analysis, products with discounts greater than 50% were selected to identify highly discounted products available on the platform.

In [30]:
high_discount_products = df[df['discount'] > 50]
high_discount_products[['title', 'category', 'discount', 'final_price']].head()

         title     category  discount  final_price
0  Lino Perros    backpacks      58.0  "₹3,995.00"
2        Lavie    backpacks      65.0  "₹2,999.00"
3       F Gear    backpacks      52.0  "₹1,675.00"
6   AVI Living  bath-towels      65.0  "₹1,399.00"
7      My Room    bedsheets      54.0  "₹2,999.00"

## 5.Remove duplicates.

In [12]:
#Duplicate Records
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [31]:
#Sum of Duplicate Records
df.duplicated().sum()

0

## 6. Derived Column Creation

The assignment suggests creating a derived column such as:

total_amount = price × quantity

However, after exploring the dataset, it was observed that the dataset does not contain a quantity column. Therefore, creating the exact derived feature suggested in the assignment was not possible.

An alternative feature called **Popularity Score** was created using the available attributes:

- Rating
- Ratings Count

The purpose of this feature is to identify products that are both highly rated and frequently reviewed.

Formula:

Popularity Score = Rating × Ratings Count

A product with a high rating and a large number of reviews is generally more popular and trusted by customers.

This derived feature provides meaningful business insight and helps compare products based on both quality and customer engagement.

In [44]:
df[['rating','ratings_count']].head(10)

   rating  ratings_count
0     3.8             15
1     4.5             67
2     4.4            226
3     4.4           1052
4     4.7             12
5     4.5             42
6     4.0              5
7     4.7             10
8     4.5             22
9     3.7              7

In [45]:
df[['rating','ratings_count']].dtypes

rating           float64
ratings_count      int64
dtype: object

In [48]:
#Creating a new Column using 'rating' and 'rating_score'
df['popularity_score'] = df['rating'] * df['ratings_count']
df[['title', 'rating', 'ratings_count', 'popularity_score']].head(10)

            title  rating  ratings_count  popularity_score
0     Lino Perros     3.8             15              57.0
1  Tommy Hilfiger     4.5             67             301.5
2           Lavie     4.4            226             994.4
3          F Gear     4.4           1052            4628.8
4       MYTRIDENT     4.7             12              56.4
5             H&M     4.5             42             189.0
6      AVI Living     4.0              5              20.0
7         My Room     4.7             10              47.0
8         My Room     4.5             22              99.0
9      Story@home     3.7              7              25.9

## 7.Save the cleaned dataset as a new CSV file.

In [59]:
df.to_csv('cleaned_dataset.csv', index=False)
print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [56]:
df.shape

(1000, 23)

In [58]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'seller_name', 'sizes',
       'seller_information', 'variations', 'best_offer', 'more_offers',
       'category', 'popularity_score'],
      dtype='object')

## Summary

In this assignment, a shopping dataset was explored, cleaned, and transformed using Pandas.

The following tasks were successfully completed:

1. Loaded the dataset into a Pandas DataFrame.
2. Explored the dataset using head(), shape, columns, and info().
3. Identified missing values and analyzed their impact.
4. Removed non-essential columns with a high percentage of missing values.
5. Filled missing values in important business-related columns.
6. Verified that no duplicate records were present.
7. Performed basic data operations such as selecting columns and filtering rows.
8. Created a new derived feature called `popularity_score` using product ratings and rating counts.
9. Saved the cleaned dataset as a new CSV file.

The dataset is now cleaner, more consistent, and better suited for further analysis.

## Key Insights

During the analysis, several observations were made:

- The dataset contains products from multiple shopping categories.
- Missing values were primarily concentrated in descriptive fields such as videos and customer reviews.
- Product ratings generally ranged between 3 and 5.
- Many products offered significant discounts.
- The newly created popularity_score feature helps identify products that are both highly rated and frequently reviewed.

These observations provide a better understanding of the dataset and demonstrate how exploratory analysis can reveal useful business insights.